### ISSUE TITLE
Remove References to Legacy MongoDB Driver

### ISSUE THREAD

**Issue by wespday** [sbmako/NServiceBus.MongoDB#11]
Should fix this build warning:

    Internals\MongoHelpers.cs(46,26): warning CS0618:
    'MongoDB.Driver.MongoClientExtensions.GetServer(MongoDB.Driver.MongoClient)'
    is obsolete: 'Use the new API instead.'

Also, remove references to *MongoDB.Driver.Legacy.dll*

**Comment by wespday** [comment]
Probably best to wait until the MongoDB C# Driver version 2.1 is released.
That release is planned to re-introduce AsQueryable and GridFS.
For now we still have the legacy driver with a warning ;).

See the **GridFS with new C# 2.0 Driver** issue: https://jira.mongodb.org/browse/CSHARP-1247

and also the discussion on **AsQueryable**:
https://groups.google.com/forum/#!msg/mongodb-user/ZMtmndAuMZs/9XdirPhCZ5MJ

See also the upgrading to 2.0 Reference:
http://mongodb.github.io/mongo-csharp-driver/2.0/upgrading/

**Comment by sbmako** [comment]
Done in v6
