### ISSUE TITLE
Element name 'NServiceBus.MessageId' is not valid'

### ISSUE THREAD

**Issue by curlyfro** [sbmako/NServiceBus.MongoDB#15]
mongocsharpdriver" version="2.0.1" targetFramework="net451"
MongoDB.Bson" version="2.0.1" targetFramework="net45"
MongoDB.Driver" version="2.0.1" targetFramework="net45"
MongoDB.Driver.Core" version="2.0.1" targetFramework="net45"
NServiceBus" version="5.2.4" targetFramework="net451"
NServiceBus.MongoDB" version="2.1.0" targetFramework="net45"

using msmq. after upgrading nservicebus from 5.2.2 and the mongo drivers to 2.0+ i'm getting an error after my 'RequestTimeout' call. if i use InMemoryPersistence, this error goes away which suggests it's something with the nservicebus mongo driver. has anyone have any ideas?

2015-08-10 12:08:46.471 INFO NServiceBus.Unicast.Transport.TransportReceiver Failed to process message
MongoDB.Bson.BsonSerializationException: Element name 'NServiceBus.MessageId' is not valid'.
at MongoDB.Bson.IO.BsonWriter.WriteName(String name)
at MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer.SerializeValue(BsonSerializationContext context, BsonSerializationArgs args, BsonDocument value)

**Comment by sbmako** [comment]
I think the issues i am having with the latest NSB acceptance tests is related to this issue.  I have corrected a few things and should have the code passing all the tests soon.   I will be pushing these changes soon.

**Comment by sbmako** [comment]
Resolved.  Will  be available in next build.

**Comment by curlyfro** [comment]
error with the latest.

namespace NServiceBus.MongoDB.TimeoutPersister 
MongoTimeoutPersister.cs line 202.

An exception of type 'MongoDB.Driver.MongoWriteConcernException' occurred in MongoDB.Driver.Legacy.dll but was not handled in user code

Additional information: WriteConcern detected an error 'Trying to create an index with same name OwningTimeoutManagerAndTime with different key spec { Time: 1, OwningTimeoutManager: 1 } vs existing spec { OwningTimeoutManager: 1, Time: 1 }'. (Response was { "ok" : 1, "code" : 67, "err" : "Trying to create an index with same name OwningTimeoutManagerAndTime with different key spec { Time: 1, OwningTimeoutManager: 1 } vs existing spec { OwningTimeoutManager: 1, Time: 1 }", "n" : NumberLong(0) }).

**Comment by sbmako** [comment]
Drop the index and let it get re-created.  The index was updated to put Time before OwningTimeoutManager.

**Comment by curlyfro** [comment]
that worked.  thanks :)
