### ISSUE TITLE
Adjust to changes in timeouts persistence interface in NServiceBus

### ISSUE THREAD

**Issue by weralabaj** [sbmako/NServiceBus.MongoDB#20]
Recently we discovered an edge case scenario in timeouts persistence that might lead to a message loss. To address this issue we decided to introduce a breaking change (new interface across versions 4.4-5.3) and adapt all persistence providers we support.
You can find more details on the issue here https://github.com/Particular/NServiceBus/issues/2885.
Please, contact as asap so we can provide further details (weronika.labaj@particular.net), walk you through the changes we're making and explain what is the impact for this project.

Weronika Łabaj
Particular Software

**Comment by adrilort** [comment]
Hi @weralabaj I've made a pull request fixing this issue. Hope @sbmako can merge it to master.

**Comment by sbmako** [comment]
merged in.
