### ISSUE TITLE
Remove subscription versioning based on assembly version

### ISSUE THREAD

**Issue by andreasohlund** [sbmako/NServiceBus.MongoDB#28]
We've recently concluded that including the major version of the assembly containing the message contracts could lead to message loss for users not aware of this behavior. NServiceBus core 5.2.17 was released to fix this https://github.com/Particular/NServiceBus/pull/4177.

Looking at the code I think the same problem exists here. I even think it could be worse since `SubscriptionKey` stores both the type name and the full version. And I guess that both are compared and not just the `major` part of the version.

What can we do to only story the type name and ignore the version completely?

**Comment by sbmako** [comment]
I will take care of that.  Will remove the version number completely.

**Comment by sbmako** [comment]
Done.

**Comment by andreasohlund** [comment]
Awesome. v7 will change the api to not even pass the version down to the
persister

https://github.com/Particular/NServiceBus/issues/4175
