### ISSUE TITLE
Add subscription specific example

### ISSUE THREAD

**Issue by sbmako** [sbmako/NServiceBus.MongoDB#4]
Add a complete sample of a publish and subscribe example with single publisher and at least two subscribers.

**Comment by SimonCropp** [comment]
this has a subscriber http://docs.particular.net/samples/mongodb/ 
good enough to get u started?

**Comment by sbmako** [comment]
Thanks, ok to just link to it?

**Comment by SimonCropp** [comment]
fine with me :)

BTW appreciate a review of the sample. i have used mongo before but this is the first time combined with NSB.

**Comment by sbmako** [comment]
The sample looks great.  Not sure how you feel about using ContainsSagaData, but there is also an included ContainsMongoSagaData that takes care of the IHaveDocumentVersion.

**Comment by sbmako** [comment]
Thanks @SimonCropp  for the example.
